// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9psOMAsuSG8YF2hcz03ViQ-Gwo_Iefro',
    appId: '1:441878211691:web:7fce7b38dac0d26426952e',
    messagingSenderId: '441878211691',
    projectId: 'tele-health-a0d35',
    authDomain: 'tele-health-a0d35.firebaseapp.com',
    storageBucket: 'tele-health-a0d35.firebasestorage.app',
    measurementId: 'G-VVJECS3J2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9pO0gA5SFiEJNrrX3_bWBYzJbxhkhWNU',
    appId: '1:441878211691:android:75f8cc83419d159526952e',
    messagingSenderId: '441878211691',
    projectId: 'tele-health-a0d35',
    storageBucket: 'tele-health-a0d35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0eTB0KRpjpRDSIEue2sSPxNID6r9f-H4',
    appId: '1:441878211691:ios:f20a4c1271fa747f26952e',
    messagingSenderId: '441878211691',
    projectId: 'tele-health-a0d35',
    storageBucket: 'tele-health-a0d35.firebasestorage.app',
    iosBundleId: 'com.example.telehealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0eTB0KRpjpRDSIEue2sSPxNID6r9f-H4',
    appId: '1:441878211691:ios:f20a4c1271fa747f26952e',
    messagingSenderId: '441878211691',
    projectId: 'tele-health-a0d35',
    storageBucket: 'tele-health-a0d35.firebasestorage.app',
    iosBundleId: 'com.example.telehealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9psOMAsuSG8YF2hcz03ViQ-Gwo_Iefro',
    appId: '1:441878211691:web:d91f9dc04b381ea426952e',
    messagingSenderId: '441878211691',
    projectId: 'tele-health-a0d35',
    authDomain: 'tele-health-a0d35.firebaseapp.com',
    storageBucket: 'tele-health-a0d35.firebasestorage.app',
    measurementId: 'G-RM182X3FE7',
  );
}
