// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA30Von4xQ6ienuTMJqhkhbXlQPz7ofZh8',
    appId: '1:181933459116:web:579052daca44af1cb10109',
    messagingSenderId: '181933459116',
    projectId: 'telehealth-app-b51b9',
    authDomain: 'telehealth-app-b51b9.firebaseapp.com',
    storageBucket: 'telehealth-app-b51b9.firebasestorage.app',
    measurementId: 'G-Z2GNB2NH1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq9QmU10ISSCm5JgbjOe-WqXf935WLxBg',
    appId: '1:181933459116:android:7c8c1c8133b4ede3b10109',
    messagingSenderId: '181933459116',
    projectId: 'telehealth-app-b51b9',
    storageBucket: 'telehealth-app-b51b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaA9Jnt2HHvMVmTMFJ3ZJVOvIGz2h2ntI',
    appId: '1:181933459116:ios:b101bd3f42c85078b10109',
    messagingSenderId: '181933459116',
    projectId: 'telehealth-app-b51b9',
    storageBucket: 'telehealth-app-b51b9.firebasestorage.app',
    iosBundleId: 'com.example.telehealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaA9Jnt2HHvMVmTMFJ3ZJVOvIGz2h2ntI',
    appId: '1:181933459116:ios:b101bd3f42c85078b10109',
    messagingSenderId: '181933459116',
    projectId: 'telehealth-app-b51b9',
    storageBucket: 'telehealth-app-b51b9.firebasestorage.app',
    iosBundleId: 'com.example.telehealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA30Von4xQ6ienuTMJqhkhbXlQPz7ofZh8',
    appId: '1:181933459116:web:aeac7f1f05379c95b10109',
    messagingSenderId: '181933459116',
    projectId: 'telehealth-app-b51b9',
    authDomain: 'telehealth-app-b51b9.firebaseapp.com',
    storageBucket: 'telehealth-app-b51b9.firebasestorage.app',
    measurementId: 'G-VWKP4BKRDW',
  );

}